[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "opencv-python>=4.12.0.88",
    "pyzbar>=0.1.9",
    "werkzeug>=3.1.3",
    "zxing-cpp>=2.3.0",
]
